# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCustomerCRUD():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()

  def teardown_method(self, method):
    self.driver.quit()

  def test_customerCRUD(self):
    self.driver.get("http://127.0.0.1:8000/login")
    self.driver.set_window_size(974, 1080)
    self.driver.find_element(By.ID, "email").send_keys("admin@inspectietool.nl")
    self.driver.implicitly_wait(10)
    self.driver.find_element(By.ID, "password").send_keys("password")
    self.driver.implicitly_wait(10)
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.implicitly_wait(10)
    self.driver.find_element(By.LINK_TEXT, "Klanten").click()
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.LINK_TEXT, "Toevoegen").click()
    self.driver.implicitly_wait(5)
    time.sleep(5)
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("TestBedrijf")
    time.sleep(5)
    self.driver.find_element(By.ID, "street").click()
    self.driver.find_element(By.ID, "street").send_keys("teststraat 12")
    time.sleep(5)
    self.driver.find_element(By.ID, "postal_code").click()
    self.driver.find_element(By.ID, "postal_code").send_keys("5223KT")
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.ID, "phone_number").click()
    self.driver.find_element(By.ID, "phone_number").send_keys("061234567")
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.ID, "number").click()
    self.driver.find_element(By.ID, "number").send_keys("215")
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.ID, "city").click()
    self.driver.find_element(By.ID, "city").send_keys("den bosch")
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.ID, "contact_name").click()
    self.driver.find_element(By.ID, "contact_name").send_keys("testpersoon")
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.ID, "contact_phone_number").click()
    self.driver.find_element(By.ID, "contact_phone_number").send_keys("0612345678")
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.ID, "contact_email").click()
    self.driver.find_element(By.ID, "contact_email").send_keys("test@email.com")
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.CSS_SELECTOR, ".float-right").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-arrow-right-short").click()
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.ID, "switchButton").click()
    time.sleep(5)
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("Test")
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.ID, "saveButton").click()
    self.driver.implicitly_wait(5)
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".bi-arrow-right-short").click()
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.ID, "switchButton").click()
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.ID, "archiveButton").click()
    self.driver.implicitly_wait(5)
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.LINK_TEXT, "Archief").click()
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.LINK_TEXT, "Verwijder alles").click()
    self.driver.implicitly_wait(5)
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.LINK_TEXT, "admin").click()
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.LINK_TEXT, "Uitloggen").click()

