# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestInspectionTypeCRUD():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_inspectionTypeCRUD(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(982, 1050)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Inspectietypes").click()
    self.driver.find_element(By.LINK_TEXT, "Toevoegen").click()
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("naam")
    self.driver.find_element(By.NAME, "description").send_keys("beschrijving")
    self.driver.find_element(By.NAME, "color").click()
    self.driver.find_element(By.NAME, "color").send_keys("#ff0000")
    self.driver.find_element(By.NAME, "icon_id").click()
    dropdown = self.driver.find_element(By.NAME, "icon_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Magnet']").click()
    self.driver.find_element(By.NAME, "icon_id").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\31 > .bi").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > h1").click()
    self.driver.find_element(By.ID, "switchButton").click()
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("Brandblussers1")
    self.driver.find_element(By.NAME, "description").click()
    self.driver.find_element(By.NAME, "description").send_keys("Alle brandblussers moeten niet over de datum zijn.1")
    self.driver.find_element(By.NAME, "icon_id").click()
    dropdown = self.driver.find_element(By.NAME, "icon_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Fire']").click()
    self.driver.find_element(By.NAME, "icon_id").click()
    self.driver.find_element(By.NAME, "color").click()
    self.driver.find_element(By.NAME, "color").send_keys("#ff9494")
    self.driver.find_element(By.ID, "saveButton").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\31 > .bi").click()
    self.driver.find_element(By.ID, "switchButton").click()
    self.driver.find_element(By.ID, "archiveButton").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
